
###  STORE 프로젝트
# @no-cookie-jar
POST http://localhost:8383/auth/register
Content-Type: application/json

{
  "email": "test1@naver.com",
  "password": "gksrlqja1!",
  "name": "점주1"
}

###                        -------------           로그인 처리 (토큰 발급)            --------------
# @no-cookie-jar
POST http://localhost:8383/auth/login
Content-Type: application/json

{
  "email": "test1@naver.com",
  "password": "gksrlqja1!"
}


<> 2025-03-08T093843.200.json
<> 2025-03-07T195614.200.json
<> 2025-03-07T185221.200.json



###
# @no-cookie-jar
POST http://localhost:8383/auth/logout


###
# @no-cookie-jar
POST http://localhost:8383/api/stores
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiT1dORVIiLCJzdG9yZUlkTGlzdCI6WzEsMyw0XSwidXNlcklkIjoxLCJpc3MiOiJzdG9yZSIsImlhdCI6MTc0MjE3MTMyNiwiZXhwIjoxNzQyMTc4NTI2LCJzdWIiOiIxIn0.sdpZZjWE3sozt0P1Uyq8ZAc-AegHYbW6kY9V7JTHTrg

{
  "password": "1234",
  "storeName": "롯데슈퍼",
  "storePlace": "서북구 한들2로 123",
  "phoneNumber": "01012342345"
}

###
# @no-cookie-jar
GET http://localhost:8383/api/stores
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiT1dORVIiLCJzdG9yZUlkTGlzdCI6WzFdLCJ1c2VySWQiOjEsImlzcyI6InN0b3JlIiwiaWF0IjoxNzQxNDA4NjI1LCJleHAiOjE3NDE0MTU4MjUsInN1YiI6IjEifQ.BJJSoUjNlTf_jMrhOWYpF9Dn3ezFUlML02EgGdDHQTc

###
# @no-cookie-jar
POST http://localhost:8383/api/stores/login
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiT1dORVIiLCJzdG9yZUlkTGlzdCI6WzFdLCJ1c2VySWQiOjEsImlzcyI6InN0b3JlIiwiaWF0IjoxNzQxNDA4NjI1LCJleHAiOjE3NDE0MTU4MjUsInN1YiI6IjEifQ.BJJSoUjNlTf_jMrhOWYpF9Dn3ezFUlML02EgGdDHQTc

{
  "storeId": 1,
  "password": "1234"
}


###
# @no-cookie-jar
PATCH http://localhost:8383/api/stores
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiT1dORVIiLCJzdG9yZUlkTGlzdCI6WzFdLCJ1c2VySWQiOjEsImlzcyI6InN0b3JlIiwiaWF0IjoxNzQxNDA4NjI1LCJleHAiOjE3NDE0MTU4MjUsInN1YiI6IjEifQ.BJJSoUjNlTf_jMrhOWYpF9Dn3ezFUlML02EgGdDHQTc

{
  "storeId": 1,
  "storeName": "맘스터치",
  "storePlace": "서북구 한들 3로 100",
  "password": "1234",
  "phoneNumber": ""
}

###
# @no-cookie-jar
DELETE http://localhost:8383/api/stores
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiT1dORVIiLCJzdG9yZUlkTGlzdCI6WzFdLCJ1c2VySWQiOjEsImlzcyI6InN0b3JlIiwiaWF0IjoxNzQxNDA4NjI1LCJleHAiOjE3NDE0MTU4MjUsInN1YiI6IjEifQ.BJJSoUjNlTf_jMrhOWYpF9Dn3ezFUlML02EgGdDHQTc

{
  "storeId": 2,
  "password": "1234"
}

###
# @no-cookie-jar
POST http://localhost:8383/api/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiT1dORVIiLCJzdG9yZUlkTGlzdCI6WzFdLCJ1c2VySWQiOjEsImlzcyI6InN0b3JlIiwiaWF0IjoxNzQxNDA4NjI1LCJleHAiOjE3NDE0MTU4MjUsInN1YiI6IjEifQ.BJJSoUjNlTf_jMrhOWYpF9Dn3ezFUlML02EgGdDHQTc

{
  "storeId": 1,
  "categoryName": "음료수",
  "colorCode": "#393939",
  "positionX": 0,
  "positionY": 0,
  "sizeType": "FULL"
}

<> 2025-02-12T200316.200.json

###
# @no-cookie-jar
GET http://localhost:8383/api/categories/all/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiT1dORVIiLCJzdG9yZUlkTGlzdCI6WzFdLCJ1c2VySWQiOjEsImlzcyI6InN0b3JlIiwiaWF0IjoxNzQxNDA4NjI1LCJleHAiOjE3NDE0MTU4MjUsInN1YiI6IjEifQ.BJJSoUjNlTf_jMrhOWYpF9Dn3ezFUlML02EgGdDHQTc

<> 2025-02-20T204105.200.json
<> 2025-02-15T150218.200.json

###
# @no-cookie-jar
GET http://localhost:8383/api/categories/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiT1dORVIiLCJzdG9yZUlkTGlzdCI6WzFdLCJ1c2VySWQiOjEsImlzcyI6InN0b3JlIiwiaWF0IjoxNzQxNDA4NjI1LCJleHAiOjE3NDE0MTU4MjUsInN1YiI6IjEifQ.BJJSoUjNlTf_jMrhOWYpF9Dn3ezFUlML02EgGdDHQTc

###
POST http://localhost:8383/auth/refresh
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiT1dORVIiLCJzdG9yZUlkTGlzdCI6WzEsMiw4XSwidXNlcklkIjoxLCJpc3MiOiJzdG9yZSIsImlhdCI6MTc0MDU0ODk2OSwiZXhwIjoxNzQxMTUzNzY5LCJzdWIiOiIxIn0.WM4kZsMWhWuivKawob7T8qAkkvL1HN8FRxO6nFcisc4"
}

###
# @no-cookie-jar
PATCH http://localhost:8383/api/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiT1dORVIiLCJzdG9yZUlkTGlzdCI6WzFdLCJ1c2VySWQiOjEsImlzcyI6InN0b3JlIiwiaWF0IjoxNzQxNDA4NjI1LCJleHAiOjE3NDE0MTU4MjUsInN1YiI6IjEifQ.BJJSoUjNlTf_jMrhOWYpF9Dn3ezFUlML02EgGdDHQTc

{
  "categoryId": 1,
  "uiId": 1,
  "categoryName": "행사메뉴",
  "colorCode": "#3A3A3A",
  "positionX": 0,
  "positionY": 0,
  "sizeType": "FULL"
}

###
DELETE http://localhost:8383/api/categories/14
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiT1dORVIiLCJzdG9yZUlkTGlzdCI6WzEsMl0sInVzZXJJZCI6MSwiaXNzIjoic3RvcmUiLCJpYXQiOjE3NDA1NDkxOTgsImV4cCI6MTc0MDU1NjM5OCwic3ViIjoiMSJ9.52TKLLkrnManqwgT0Wi1dyFwjtcDuGd9EFXwKqg54eY

###
# @no-cookie-jar
POST http://localhost:8383/api/menus
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiT1dORVIiLCJzdG9yZUlkTGlzdCI6WzFdLCJ1c2VySWQiOjEsImlzcyI6InN0b3JlIiwiaWF0IjoxNzQxNDA4NjI1LCJleHAiOjE3NDE0MTU4MjUsInN1YiI6IjEifQ.BJJSoUjNlTf_jMrhOWYpF9Dn3ezFUlML02EgGdDHQTc

{
  "categoryId": 5,
  "storeId": 1,
  "menuName": "사이다",
  "discountRate": 0,
  "price": 2000,
  "colorCode": "",
  "positionX": 0,
  "positionY": 0,
  "sizeType": ""
}

###
# @no-cookie-jar
GET http://localhost:8383/api/menus/all/3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiT1dORVIiLCJzdG9yZUlkTGlzdCI6WzFdLCJ1c2VySWQiOjEsImlzcyI6InN0b3JlIiwiaWF0IjoxNzQxNDA4NjI1LCJleHAiOjE3NDE0MTU4MjUsInN1YiI6IjEifQ.BJJSoUjNlTf_jMrhOWYpF9Dn3ezFUlML02EgGdDHQTc

<> 2025-02-15T093816.200.json

###
# @no-cookie-jar
GET http://localhost:8383/api/menus/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiT1dORVIiLCJzdG9yZUlkTGlzdCI6WzFdLCJ1c2VySWQiOjEsImlzcyI6InN0b3JlIiwiaWF0IjoxNzQxNDA4NjI1LCJleHAiOjE3NDE0MTU4MjUsInN1YiI6IjEifQ.BJJSoUjNlTf_jMrhOWYpF9Dn3ezFUlML02EgGdDHQTc

###
PATCH http://localhost:8383/api/menus
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiT1dORVIiLCJzdG9yZUlkTGlzdCI6WzEsMl0sInVzZXJJZCI6MSwiaXNzIjoic3RvcmUiLCJpYXQiOjE3NDAzOTI3MjYsImV4cCI6MTc0MDM5OTkyNiwic3ViIjoiMSJ9.Oo9lPLWsFEibXl0k80i0yJRhtKVS85VbFjOLEojYehk

{
  "menuId": 1,
  "menuName": "싸이버거",
  "discountRate": 0,
  "price": 5300,
  "colorCode": "#FAFAFA",
  "positionX": 100,
  "positionY": 200,
  "sizeType": "FULL"
}

###
DELETE http://localhost:8383/api/menus/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdG9yZSIsImlhdCI6MTczOTUxNTkxNCwiZXhwIjoxNzM5NTE5NTE0LCJzdWIiOiIxMiJ9.jZnVRm74RdDZkMv1A_OIJQKvxxixBtUuUkx4jNoGPcY

###
# @no-cookie-jar
POST http://localhost:8383/api/places
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiT1dORVIiLCJzdG9yZUlkTGlzdCI6WzFdLCJ1c2VySWQiOjEsImlzcyI6InN0b3JlIiwiaWF0IjoxNzQxNDA4NjI1LCJleHAiOjE3NDE0MTU4MjUsInN1YiI6IjEifQ.BJJSoUjNlTf_jMrhOWYpF9Dn3ezFUlML02EgGdDHQTc

{
  "storeId": 1,
  "placeName": "창가3",
  "positionX": 0,
  "positionY": 0,
  "sizeType": "FULL"
}

###
# @no-cookie-jar
GET http://localhost:8383/api/places/all/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiT1dORVIiLCJzdG9yZUlkTGlzdCI6WzFdLCJ1c2VySWQiOjEsImlzcyI6InN0b3JlIiwiaWF0IjoxNzQxNDA4NjI1LCJleHAiOjE3NDE0MTU4MjUsInN1YiI6IjEifQ.BJJSoUjNlTf_jMrhOWYpF9Dn3ezFUlML02EgGdDHQTc

###
# @no-cookie-jar
GET http://localhost:8383/api/places/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiT1dORVIiLCJzdG9yZUlkTGlzdCI6WzFdLCJ1c2VySWQiOjEsImlzcyI6InN0b3JlIiwiaWF0IjoxNzQxNDA4NjI1LCJleHAiOjE3NDE0MTU4MjUsInN1YiI6IjEifQ.BJJSoUjNlTf_jMrhOWYpF9Dn3ezFUlML02EgGdDHQTc


###
PATCH http://localhost:8383/api/places
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiT1dORVIiLCJzdG9yZUlkTGlzdCI6WzEsMl0sInVzZXJJZCI6MSwiaXNzIjoic3RvcmUiLCJpYXQiOjE3NDA1NDkxOTgsImV4cCI6MTc0MDU1NjM5OCwic3ViIjoiMSJ9.52TKLLkrnManqwgT0Wi1dyFwjtcDuGd9EFXwKqg54eY

{
  "placeId": 4,
  "placeName": "수정1",
  "sizeType": "FULL",
  "positionX": 0,
  "positionY": 0
}

<> 2025-02-26T150229.200.json
<> 2025-02-14T173217.200.json

###
DELETE http://localhost:8383/api/places/3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiT1dORVIiLCJzdG9yZUlkTGlzdCI6WzEsMl0sInVzZXJJZCI6MSwiaXNzIjoic3RvcmUiLCJpYXQiOjE3NDAzOTI3MjYsImV4cCI6MTc0MDM5OTkyNiwic3ViIjoiMSJ9.Oo9lPLWsFEibXl0k80i0yJRhtKVS85VbFjOLEojYehk


<> 2025-03-07T155206.200.json
<> 2025-02-24T192928-1.200.json

###
# @no-cookie-jar
POST http://localhost:8383/api/orders/add/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiT1dORVIiLCJzdG9yZUlkTGlzdCI6WzFdLCJ1c2VySWQiOjEsImlzcyI6InN0b3JlIiwiaWF0IjoxNzQxNDA4NjI1LCJleHAiOjE3NDE0MTU4MjUsInN1YiI6IjEifQ.BJJSoUjNlTf_jMrhOWYpF9Dn3ezFUlML02EgGdDHQTc

{
  "storeId": 1,
  "placeId": 1,
  "items": [
    {
      "menuId": 6,
      "quantity": 2
    }
  ]
}

###
GET http://localhost:8383/api/orders/detail/28
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiT1dORVIiLCJzdG9yZUlkTGlzdCI6WzEsMl0sInVzZXJJZCI6MSwiaXNzIjoic3RvcmUiLCJpYXQiOjE3NDA5OTA5MTQsImV4cCI6MTc0MDk5ODExNCwic3ViIjoiMSJ9.QmyEf0aZV1RjAg_1UkOcmtO7oESvl_DunVCv-OfDvmk

###
# @no-cookie-jar
GET http://localhost:8383/api/pay/all/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiT1dORVIiLCJzdG9yZUlkTGlzdCI6WzFdLCJ1c2VySWQiOjEsImlzcyI6InN0b3JlIiwiaWF0IjoxNzQxNDA4NjI1LCJleHAiOjE3NDE0MTU4MjUsInN1YiI6IjEifQ.BJJSoUjNlTf_jMrhOWYpF9Dn3ezFUlML02EgGdDHQTc

###
# @no-cookie-jar
GET http://localhost:8383/api/pay/detail?paymentId=3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiT1dORVIiLCJzdG9yZUlkTGlzdCI6WzFdLCJ1c2VySWQiOjEsImlzcyI6InN0b3JlIiwiaWF0IjoxNzQxNDA4NjI1LCJleHAiOjE3NDE0MTU4MjUsInN1YiI6IjEifQ.BJJSoUjNlTf_jMrhOWYpF9Dn3ezFUlML02EgGdDHQTc


<> 2025-02-23T202043.200.json

###
# @no-cookie-jar
POST http://localhost:8383/api/times/open/3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiT1dORVIiLCJzdG9yZUlkTGlzdCI6WzEsM10sInVzZXJJZCI6MSwiaXNzIjoic3RvcmUiLCJpYXQiOjE3NDE1MTg1ODMsImV4cCI6MTc0MTUyNTc4Mywic3ViIjoiMSJ9.SvuznV6aToEk1SAuQlSMdavlNGWBShTNDas3fABmNXs

<> 2025-03-08T093943.200.json
<> 2025-02-25T134731.200.json

###
# @no-cookie-jar
POST http://localhost:8383/api/times/close/3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiT1dORVIiLCJzdG9yZUlkTGlzdCI6WzEsM10sInVzZXJJZCI6MSwiaXNzIjoic3RvcmUiLCJpYXQiOjE3NDE1MTg1ODMsImV4cCI6MTc0MTUyNTc4Mywic3ViIjoiMSJ9.SvuznV6aToEk1SAuQlSMdavlNGWBShTNDas3fABmNXs

<> 2025-03-08T095722.200.json
<> 2025-03-08T095322.200.json

###
# @no-cookie-jar
GET http://localhost:8383/api/reports/all/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiT1dORVIiLCJzdG9yZUlkTGlzdCI6WzFdLCJ1c2VySWQiOjEsImlzcyI6InN0b3JlIiwiaWF0IjoxNzQxNDA4NjI1LCJleHAiOjE3NDE0MTU4MjUsInN1YiI6IjEifQ.BJJSoUjNlTf_jMrhOWYpF9Dn3ezFUlML02EgGdDHQTc


###
# @no-cookie-jar
GET http://localhost:8383/api/reports?storeId=1&startDate=2025-02-22&endDate=2025-03-08
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiT1dORVIiLCJzdG9yZUlkTGlzdCI6WzFdLCJ1c2VySWQiOjEsImlzcyI6InN0b3JlIiwiaWF0IjoxNzQxNDA4NjI1LCJleHAiOjE3NDE0MTU4MjUsInN1YiI6IjEifQ.BJJSoUjNlTf_jMrhOWYpF9Dn3ezFUlML02EgGdDHQTc

<> 2025-03-07T205206.200.json
<> 2025-03-07T205159.200.json
<> 2025-03-07T205153.200.json

###
# @no-cookie-jar
GET http://localhost:8383/api/reports/daily?storeId=1&date=2025-03-08&page=1&size=10&status=all
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiT1dORVIiLCJzdG9yZUlkTGlzdCI6WzEsMyw0XSwidXNlcklkIjoxLCJpc3MiOiJzdG9yZSIsImlhdCI6MTc0MjM1OTUwNiwiZXhwIjoxNzQyMzY2NzA2LCJzdWIiOiIxIn0.erhZ6cLO9lfPx2VMoe_Bwr0kMWTZUjl0VgcW7kVF93M

<> 2025-03-07T205443.200.json
<> 2025-03-07T205305.200.json
<> 2025-03-07T205220.200.json


###
# @no-cookie-jar
GET http://localhost:8383/api/reports/average?storeId=1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiT1dORVIiLCJzdG9yZUlkTGlzdCI6WzFdLCJ1c2VySWQiOjEsImlzcyI6InN0b3JlIiwiaWF0IjoxNzQxNDA4NjI1LCJleHAiOjE3NDE0MTU4MjUsInN1YiI6IjEifQ.BJJSoUjNlTf_jMrhOWYpF9Dn3ezFUlML02EgGdDHQTc

<> 2025-03-07T205535.200.json

###
# @no-cookie-jar
GET http://localhost:8383/api/reports/categories?storeId=1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiT1dORVIiLCJzdG9yZUlkTGlzdCI6WzFdLCJ1c2VySWQiOjEsImlzcyI6InN0b3JlIiwiaWF0IjoxNzQxNDA4NjI1LCJleHAiOjE3NDE0MTU4MjUsInN1YiI6IjEifQ.BJJSoUjNlTf_jMrhOWYpF9Dn3ezFUlML02EgGdDHQTc

<> 2025-03-07T205545.200.json

### report about peaktime
# @no-cookie-jar
GET http://localhost:8383/api/reports/peak-time?storeId=1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiT1dORVIiLCJzdG9yZUlkTGlzdCI6WzFdLCJ1c2VySWQiOjEsImlzcyI6InN0b3JlIiwiaWF0IjoxNzQxNDA4NjI1LCJleHAiOjE3NDE0MTU4MjUsInN1YiI6IjEifQ.BJJSoUjNlTf_jMrhOWYpF9Dn3ezFUlML02EgGdDHQTc

<> 2025-03-07T205558.200.json

### card vs cash get average
# @no-cookie-jar
GET http://localhost:8383/api/reports/payment-type?storeId=1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiT1dORVIiLCJzdG9yZUlkTGlzdCI6WzFdLCJ1c2VySWQiOjEsImlzcyI6InN0b3JlIiwiaWF0IjoxNzQxNDA4NjI1LCJleHAiOjE3NDE0MTU4MjUsInN1YiI6IjEifQ.BJJSoUjNlTf_jMrhOWYpF9Dn3ezFUlML02EgGdDHQTc

<> 2025-03-07T205700.200.json
<> 2025-03-07T205612.200.json

### placeId로 주문정보 찾기
# @no-cookie-jar
GET http://localhost:8383/api/orders/places/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiT1dORVIiLCJzdG9yZUlkTGlzdCI6WzFdLCJ1c2VySWQiOjEsImlzcyI6InN0b3JlIiwiaWF0IjoxNzQxNDA4NjI1LCJleHAiOjE3NDE0MTU4MjUsInN1YiI6IjEifQ.BJJSoUjNlTf_jMrhOWYpF9Dn3ezFUlML02EgGdDHQTc

###
DELETE http://localhost:8383/api/orders/52
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiT1dORVIiLCJzdG9yZUlkTGlzdCI6WzEsMl0sInVzZXJJZCI6MSwiaXNzIjoic3RvcmUiLCJpYXQiOjE3NDA5OTcwMTcsImV4cCI6MTc0MTAwNDIxNywic3ViIjoiMSJ9.ib96BVFXz9V5RdYvJg8LcwzYR13L1juKCYM-n3RrTXc
Content-Type: application/json

{
  "menuId": 4,
  "quantity": 1
}

###
# @no-cookie-jar
POST http://localhost:8383/api/pay/cancel/4
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiT1dORVIiLCJzdG9yZUlkTGlzdCI6WzEsMl0sInVzZXJJZCI6MSwiaXNzIjoic3RvcmUiLCJpYXQiOjE3NDEzNDExNDEsImV4cCI6MTc0MTM0ODM0MSwic3ViIjoiMSJ9.UUbEUjCHGx226ccObkjfeo8HvWg1e9yfSSGuilBEyeU

<> 2025-03-07T185405.200.json
<> 2025-03-07T185241.404.json

###
# @no-cookie-jar
GET http://localhost:8383/api/receipts/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiT1dORVIiLCJzdG9yZUlkTGlzdCI6WzFdLCJ1c2VySWQiOjEsImlzcyI6InN0b3JlIiwiaWF0IjoxNzQxNDA4NjI1LCJleHAiOjE3NDE0MTU4MjUsInN1YiI6IjEifQ.BJJSoUjNlTf_jMrhOWYpF9Dn3ezFUlML02EgGdDHQTc

<> 2025-03-07T203351.200.json
<> 2025-03-07T203256.404.json
<> 2025-03-07T200643.500.json
<> 2025-03-07T200425.500.json
<> 2025-03-07T200320.500.json
<> 2025-03-07T195818.200.json


### 주문 생성
# @no-cookie-jar
POST http://localhost:8383/api/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiT1dORVIiLCJzdG9yZUlkTGlzdCI6WzFdLCJ1c2VySWQiOjEsImlzcyI6InN0b3JlIiwiaWF0IjoxNzQxNDk3ODQyLCJleHAiOjE3NDE1MDUwNDIsInN1YiI6IjEifQ.rCMOPnPAXIMrSBoO7M_8BH3Hgqw07Ug5CoWBWa2-toY

{
  "storeId": 1,
  "placeId": 1,
  "items": [
    {
      "menuId": 4,
      "quantity": 2
    },
    {
      "menuId": 5,
      "quantity": 2
    }
  ]
}

<> 2025-03-08T095715.200.json
<> 2025-03-08T094004.200.json
<> 2025-03-08T093909.200.json
<> 2025-03-07T201444.200.json
<> 2025-03-07T195636.200.json
<> 2025-03-07T155803.200.json


### 결제 요청
# @no-cookie-jar
POST http://localhost:8383/api/pay
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiT1dORVIiLCJzdG9yZUlkTGlzdCI6WzFdLCJ1c2VySWQiOjEsImlzcyI6InN0b3JlIiwiaWF0IjoxNzQxNDk3ODQyLCJleHAiOjE3NDE1MDUwNDIsInN1YiI6IjEifQ.rCMOPnPAXIMrSBoO7M_8BH3Hgqw07Ug5CoWBWa2-toY

{
  "storeId": 1,
  "orderId": 24,
  "placeId": 1,
  "discountAmount": 0,
  "paidMoney": 40000,
  "paymentType": "CARD",
  "cardCompany": "신한",
  "cardNumber": "1234-1234-3246-5631",
  "expiryDate": "2030/10"
}

<> 2025-03-08T094030.200.json
<> 2025-03-07T203331.200.json
<> 2025-03-07T203315.200.json
<> 2025-03-07T203304.200.json
<> 2025-03-07T195732.200.json
<> 2025-03-07T195708.200.json
<> 2025-03-07T195652.200.json
<> 2025-03-07T155900.200.json
<> 2025-03-07T155840.200.json
<> 2025-03-07T155823.200.json
<> 2025-03-07T155809.404.json
<> 2025-03-07T155612.200.json
<> 2025-03-07T155245.200.json
<> 2025-03-07T155231.200.json

###
# @no-cookie-jar
DELETE http://localhost:8383/api/orders/all/6
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiT1dORVIiLCJzdG9yZUlkTGlzdCI6WzFdLCJ1c2VySWQiOjEsImlzcyI6InN0b3JlIiwiaWF0IjoxNzQxNDg0MTQ3LCJleHAiOjE3NDE0OTEzNDcsInN1YiI6IjEifQ.lm4aIoGH4qUND0u4QRGioUbBmJZ9CTXSjIzW6X2XA4U

###
# @no-cookie-jar
GET http://localhost:8383/api/times/all-info
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiT1dORVIiLCJzdG9yZUlkTGlzdCI6WzEsM10sInVzZXJJZCI6MSwiaXNzIjoic3RvcmUiLCJpYXQiOjE3NDE1MTg1ODMsImV4cCI6MTc0MTUyNTc4Mywic3ViIjoiMSJ9.SvuznV6aToEk1SAuQlSMdavlNGWBShTNDas3fABmNXs

###
# @no-cookie-jar
POST http://localhost:8383/api/emp/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiT1dORVIiLCJzdG9yZUlkTGlzdCI6WzEsM10sInVzZXJJZCI6MSwiaXNzIjoic3RvcmUiLCJpYXQiOjE3NDE2NjgwMzAsImV4cCI6MTc0MTY3NTIzMCwic3ViIjoiMSJ9.GJM_EibGnauH_knL2Bv0zlj3eTKZeCmTtFc4gNFeWg0

{
  "password": "gksrlqja1!",
  "name": "매장1직원2",
  "profileImg": ""
}


###
# @no-cookie-jar
GET http://localhost:8383/api/emp/all/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiT1dORVIiLCJzdG9yZUlkTGlzdCI6WzEsMyw0XSwidXNlcklkIjoxLCJpc3MiOiJzdG9yZSIsImlhdCI6MTc0MTY2OTY3NCwiZXhwIjoxNzQxNjc2ODc0LCJzdWIiOiIxIn0.T9DOuAtBW_2ypglrQSl5LNreCi5od0-eDRhDU4Ntyes

###
# @no-cookie-jar
POST http://localhost:8383/api/emp/start/4
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiT1dORVIiLCJzdG9yZUlkTGlzdCI6WzEsMyw0XSwidXNlcklkIjoxLCJpc3MiOiJzdG9yZSIsImlhdCI6MTc0MTY2OTY3NCwiZXhwIjoxNzQxNjc2ODc0LCJzdWIiOiIxIn0.T9DOuAtBW_2ypglrQSl5LNreCi5od0-eDRhDU4Ntyes


###
# @no-cookie-jar
POST http://localhost:8383/api/emp/leave/4
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiT1dORVIiLCJzdG9yZUlkTGlzdCI6WzEsMyw0XSwidXNlcklkIjoxLCJpc3MiOiJzdG9yZSIsImlhdCI6MTc0MTY2OTY3NCwiZXhwIjoxNzQxNjc2ODc0LCJzdWIiOiIxIn0.T9DOuAtBW_2ypglrQSl5LNreCi5od0-eDRhDU4Ntyes

###
# @no-cookie-jar
GET http://localhost:8383/api/reports/all/1?status=success
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiT1dORVIiLCJzdG9yZUlkTGlzdCI6WzEsMyw0XSwidXNlcklkIjoxLCJpc3MiOiJzdG9yZSIsImlhdCI6MTc0MjAwMjk1MSwiZXhwIjoxNzQyMDEwMTUxLCJzdWIiOiIxIn0.rtPHUFVMSmb2oUAeYKgpbkUiFGDZTF9AaAkntQ20PNc