name: Deploy Spring Application to AWS EC2

on:
  push:
    branches:
      - feature

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: store-manager.api  # 리포지토리 루트로 체크아웃

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Make directory for deliver
        run: mkdir deploy

      - name: Write the application.yml
        run: |
          echo "${{ secrets.APPLICATION_YML }}" > ./src/main/resources/application.yml


      ## springboot 도커 이미지 빌드 후 도커허브에 push하기
      - name: Build and Push Docker Image
        working-directory: store-manager.api  # 작업 디렉토리를 리포지토리 루트로 설정
        run: |
            echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            docker buildx build --platform linux/amd64,linux/arm64 -t hankibeom/store-manager-api:latest . --push

      # 도커 허브에서 jar파일 및 pull
      - name: Deploy to Dev
        uses: appleboy/ssh-action@master
        with:
          username: ec2-user
          host: ${{ secrets.EC2_HOST }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Docker login..."
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            
            echo "Write the docker-compose.yml"
            echo "${{ secrets.DOCKER_COMPOSE_YML }}" > ./docker-compose.yml
            
            echo "Stopping existing container..."
            docker-compose down || true
            
            echo "Remove Existing Docker image..."
            docker rmi hankibeom/store-manager-api:latest || true
            
            echo "Pulling Docker image..."
            docker pull hankibeom/store-manager-api:latest
            
            echo "Starting new container..."
            docker-compose up -d 
