name: Deploy to EC2

on:
  push:
    branches:
      - feature

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: "${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}"
          restore-keys: |
            "${{ runner.os }}-gradle-"

      - name: Build with Gradle
        run: |
          ./gradlew clean build
          ls -l build/libs/

      - name: Debug Secrets
        run: |
          echo "EC2_HOST length: $(echo -n '${{ secrets.EC2_HOST }}' | wc -c)"
          echo "EC2_USER length: $(echo -n '${{ secrets.EC2_USER }}' | wc -c)"

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          echo "Stopping existing server..."
          ssh -v -o StrictHostKeyChecking=no -o ServerAliveInterval=60 $EC2_USER@$EC2_HOST "pkill -9 -f 'java -jar /home/$EC2_USER/store-manager_api-0.0.1-SNAPSHOT.jar' || true; sleep 2; ps -ef | grep 'java -jar' || true"
          echo "Uploading JAR file..."
          scp -o StrictHostKeyChecking=no build/libs/store-manager_api-0.0.1-SNAPSHOT.jar $EC2_USER@$EC2_HOST:/home/$EC2_USER/
          echo "Starting new server..."
          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST "nohup java -jar /home/$EC2_USER/store-manager_api-0.0.1-SNAPSHOT.jar &"
          echo "Deployment completed."